// lib/productsCatalog.js

const COMBI_INCLUDES = [
  "Magnetic filter",
  "Scale reducer",
  "Shock arrestor",
  "Standard horizontal flue",
  "Basic wireless programmable thermostat",
  "Chemical flush + inhibitor",
  "Old boiler removal & disposal",
  "Commissioning + registration",
];

const COMBI_NOTES = [
  "Fixed install price – must not be recalculated",
  "Vertical flue adds £300 if required",
  "Smart thermostat upgrade adds £100",
  "TRVs £35 each",
];

const SYSTEM_HEAT_INCLUDES = [
  "Magnetic filter",
  "Basic wireless programmable thermostat",
  "Chemical flush + inhibitor",
  "Old boiler removal & disposal",
  "Commissioning + registration",
];

const SYSTEM_HEAT_NOTES = [
  "Final price = boiler cost + £750 minimum margin",
  "Horizontal flue adds £150",
  "Vertical flue adds £300",
  "Smart thermostat upgrade adds £100",
  "TRVs £35 each",
];

export const PRODUCTS = [
  // Ideal Atlantic (Combi) — keep fixed prices from your existing catalogue
  {
    id: "ideal_atlantic_24",
    type: "combi",
    brand: "Ideal",
    model: "Atlantic Combi",
    warrantyYears: 5,
    kw: 24,
    priceType: "fixed",
    basePrice: 1599,
    images: ["https://drive.google.com/uc?id=1GlCOINt_HwoR8v11TjhppZH6hWnLeT8x"],
    includes: COMBI_INCLUDES,
    notes: COMBI_NOTES,
  },
  {
    id: "ideal_atlantic_30",
    type: "combi",
    brand: "Ideal",
    model: "Atlantic Combi",
    warrantyYears: 5,
    kw: 30,
    priceType: "fixed",
    basePrice: 1699,
    images: ["https://drive.google.com/uc?id=1GlCOINt_HwoR8v11TjhppZH6hWnLeT8x"],
    includes: COMBI_INCLUDES,
    notes: COMBI_NOTES,
  },
  {
    id: "ideal_atlantic_35",
    type: "combi",
    brand: "Ideal",
    model: "Atlantic Combi",
    warrantyYears: 5,
    kw: 35,
    priceType: "fixed",
    basePrice: 1849,
    images: ["https://drive.google.com/uc?id=1GlCOINt_HwoR8v11TjhppZH6hWnLeT8x"],
    includes: COMBI_INCLUDES,
    notes: COMBI_NOTES,
  },

  // Worcester Bosch Greenstar 1000 Combi — price unknown (null)
  {
    id: "wb_greenstar_1000_24",
    type: "combi",
    brand: "Worcester Bosch",
    model: "Greenstar 1000 Combi",
    warrantyYears: 5,
    kw: 24,
    priceType: "variable",
    basePrice: null,
    images: ["https://drive.google.com/uc?id=1nIbuCM2Q5GxjBf-xJ2ogKHiAHK2SzxzH"],
    includes: COMBI_INCLUDES,
    notes: COMBI_NOTES,
  },
  {
    id: "wb_greenstar_1000_30",
    type: "combi",
    brand: "Worcester Bosch",
    model: "Greenstar 1000 Combi",
    warrantyYears: 5,
    kw: 30,
    priceType: "variable",
    basePrice: null,
    images: ["https://drive.google.com/uc?id=1nIbuCM2Q5GxjBf-xJ2ogKHiAHK2SzxzH"],
    includes: COMBI_INCLUDES,
    notes: COMBI_NOTES,
  },
  {
    id: "wb_greenstar_1000_35",
    type: "combi",
    brand: "Worcester Bosch",
    model: "Greenstar 1000 Combi",
    warrantyYears: 5,
    kw: 35,
    priceType: "variable",
    basePrice: null,
    images: ["https://drive.google.com/uc?id=1nIbuCM2Q5GxjBf-xJ2ogKHiAHK2SzxzH"],
    includes: COMBI_INCLUDES,
    notes: COMBI_NOTES,
  },

  // Ideal Logic Max Combi — price unknown (null)
  {
    id: "ideal_logic_max_24",
    type: "combi",
    brand: "Ideal",
    model: "Logic Max Combi",
    warrantyYears: 10,
    kw: 24,
    priceType: "variable",
    basePrice: null,
    images: ["https://drive.google.com/uc?id=1xnDcq0fLyYvz5qG6j2Krju0T3TT3-ijy"],
    includes: COMBI_INCLUDES,
    notes: COMBI_NOTES,
  },
  {
    id: "ideal_logic_max_30",
    type: "combi",
    brand: "Ideal",
    model: "Logic Max Combi",
    warrantyYears: 10,
    kw: 30,
    priceType: "variable",
    basePrice: null,
    images: ["https://drive.google.com/uc?id=1xnDcq0fLyYvz5qG6j2Krju0T3TT3-ijy"],
    includes: COMBI_INCLUDES,
    notes: COMBI_NOTES,
  },
  {
    id: "ideal_logic_max_35",
    type: "combi",
    brand: "Ideal",
    model: "Logic Max Combi",
    warrantyYears: 10,
    kw: 35,
    priceType: "variable",
    basePrice: null,
    images: ["https://drive.google.com/uc?id=1xnDcq0fLyYvz5qG6j2Krju0T3TT3-ijy"],
    includes: COMBI_INCLUDES,
    notes: COMBI_NOTES,
  },

  // Ideal Logic System2 — price unknown in your new list (null)
  // (Pricing engine will use boilerCost + margin when you provide costs)
  {
    id: "ideal_system2_15",
    type: "system",
    brand: "Ideal",
    model: "Logic System2",
    warrantyYears: 2,
    kw: 15,
    priceType: "cost_plus",
    boilerCost: null,
    minMargin: 750,
    images: ["https://drive.google.com/uc?id=1Jny3HIkvJN9He4WOPJLi8QMzUz5u0sUe"],
    includes: SYSTEM_HEAT_INCLUDES,
    notes: SYSTEM_HEAT_NOTES,
  },
  {
    id: "ideal_system2_18",
    type: "system",
    brand: "Ideal",
    model: "Logic System2",
    warrantyYears: 2,
    kw: 18,
    priceType: "cost_plus",
    boilerCost: null,
    minMargin: 750,
    images: ["https://drive.google.com/uc?id=1Jny3HIkvJN9He4WOPJLi8QMzUz5u0sUe"],
    includes: SYSTEM_HEAT_INCLUDES,
    notes: SYSTEM_HEAT_NOTES,
  },
  {
    id: "ideal_system2_24",
    type: "system",
    brand: "Ideal",
    model: "Logic System2",
    warrantyYears: 2,
    kw: 24,
    priceType: "cost_plus",
    boilerCost: null,
    minMargin: 750,
    images: ["https://drive.google.com/uc?id=1Jny3HIkvJN9He4WOPJLi8QMzUz5u0sUe"],
    includes: SYSTEM_HEAT_INCLUDES,
    notes: SYSTEM_HEAT_NOTES,
  },

  // Baxi Heat Only 415 — price unknown (null) until trade list
  {
    id: "baxi_heat_415",
    type: "heat_only",
    brand: "Baxi",
    model: "415 Heat Only",
    warrantyYears: 5,
    kw: 15,
    priceType: "cost_plus",
    boilerCost: null,
    minMargin: 750,
    images: ["https://drive.google.com/uc?id=1qNkt_cqkCOLUTQ1Ix_XQbaDk0NTNRDSv"],
    includes: SYSTEM_HEAT_INCLUDES,
    notes: SYSTEM_HEAT_NOTES,
  },
];
